name: Supernova build tool

on: [push, pull_request]

jobs:
  build:
    name: Build for ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows",
            os: windows-latest,
            platform: "windows"
          }
        - {
            name: "Ubuntu",
            os: ubuntu-latest,
            platform: "linux"
          }
        - {
            name: "macOS",
            os: macos-latest,
            platform: "macos"
          }
          - {
            name: "Web (Emscripten)",
            os: ubuntu-latest,
            platform: "web"
          }

    steps:
      - uses: actions/checkout@v2

      - name: Install Emscripten
        if: startsWith(matrix.config.platform, 'web')
        uses: mymindstorm/setup-emsdk@v9
        with:
          version: latest-upstream
          actions-cache-folder: 'emsdk-cache'
        
      - name: Export Emscripten environment variable
        if: startsWith(matrix.config.platform, 'web')
        run: |
          export EMSCRIPTEN=$(dirname $(which emcc))

      - name: Install dependencies on Windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install cmake

      - name: Install dependencies on Ubuntu
        if: startsWith(matrix.config.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install libxi-dev libxcursor-dev libgl1-mesa-dev ninja-build cmake

      - name: Install dependencies on macOS
        if: startsWith(matrix.config.os, 'macos')
        run: |
          brew install cmake ninja

      - name: Install dependencies
        run: pip3 install --upgrade click

      - name: Build
        run: |
          cd tools/
          python3 supernova.py --build --platform ${{ matrix.config.platform }}
