name: Web

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v7
        with:
          version: latest-upstream
          actions-cache-folder: 'emsdk-cache'

      - name: Install dependencies
        run: pip3 install --upgrade click

      - name: Build with Emscripten
        run: |
          export EMSCRIPTEN=$(dirname $(which emcc))
          cd workspaces/
          python3 supernova.py --build --platform web
